// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuLYKynL0U91HS9PJaftu7NqtOzJHhN2A',
    appId: '1:169480227109:web:5115ed3308487da23c72cc',
    messagingSenderId: '169480227109',
    projectId: 'devocional-15815',
    authDomain: 'devocional-15815.firebaseapp.com',
    storageBucket: 'devocional-15815.firebasestorage.app',
    measurementId: 'G-2WLQXEVJ5S',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3rPNtSPtEwS0vU4-8eX9IK7rrJN-gvNY',
    appId: '1:169480227109:android:50c3490b471efaa93c72cc',
    messagingSenderId: '169480227109',
    projectId: 'devocional-15815',
    storageBucket: 'devocional-15815.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1xMJ8FMbiKFteVjVttOWIhYCVlvhp9IU',
    appId: '1:169480227109:ios:116971ba7fd50b003c72cc',
    messagingSenderId: '169480227109',
    projectId: 'devocional-15815',
    storageBucket: 'devocional-15815.firebasestorage.app',
    iosBundleId: 'com.felipeambrozini.devocional',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1xMJ8FMbiKFteVjVttOWIhYCVlvhp9IU',
    appId: '1:169480227109:ios:116971ba7fd50b003c72cc',
    messagingSenderId: '169480227109',
    projectId: 'devocional-15815',
    storageBucket: 'devocional-15815.firebasestorage.app',
    iosBundleId: 'com.felipeambrozini.devocional',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuLYKynL0U91HS9PJaftu7NqtOzJHhN2A',
    appId: '1:169480227109:web:26c36015a8b804f13c72cc',
    messagingSenderId: '169480227109',
    projectId: 'devocional-15815',
    authDomain: 'devocional-15815.firebaseapp.com',
    storageBucket: 'devocional-15815.firebasestorage.app',
    measurementId: 'G-43ZNRJQVPN',
  );
}
