// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
// As chaves chegam por `--dart-define` no build (GitHub Secrets no CI; o
// .env.json local via --dart-define-from-file). Mesmo caminho das chaves
// Gemini e TTS em lib/data/google.dart — e não por asset, que iria ao ar
// junto com o bundle.
const _firebaseApiKeyWeb = String.fromEnvironment('FIREBASE_API_KEY_WEB');
const _firebaseApiKeyAndroid = String.fromEnvironment('FIREBASE_API_KEY_ANDROID');
const _firebaseApiKeyIos = String.fromEnvironment('FIREBASE_API_KEY_IOS');
const _firebaseAppIdWeb = String.fromEnvironment('FIREBASE_APP_ID_WEB');
const _firebaseAppIdAndroid = String.fromEnvironment('FIREBASE_APP_ID_ANDROID');
const _firebaseAppIdIos = String.fromEnvironment('FIREBASE_APP_ID_IOS');
const _firebaseMessagingSenderId =
    String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID');
const _firebaseProjectId = String.fromEnvironment('FIREBASE_PROJECT_ID');
const _firebaseAuthDomain = String.fromEnvironment('FIREBASE_AUTH_DOMAIN');
const _firebaseStorageBucket = String.fromEnvironment('FIREBASE_STORAGE_BUCKET');
const _firebaseMeasurementId = String.fromEnvironment('FIREBASE_MEASUREMENT_ID');
const _firebaseIosClientId = String.fromEnvironment('FIREBASE_IOS_CLIENT_ID');
const _firebaseIosBundleId = String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID');

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: _firebaseApiKeyWeb,
        appId: _firebaseAppIdWeb,
        messagingSenderId: _firebaseMessagingSenderId,
        projectId: _firebaseProjectId,
        authDomain: _firebaseAuthDomain,
        storageBucket: _firebaseStorageBucket,
        measurementId: _firebaseMeasurementId,
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: _firebaseApiKeyAndroid,
        appId: _firebaseAppIdAndroid,
        messagingSenderId: _firebaseMessagingSenderId,
        projectId: _firebaseProjectId,
        storageBucket: _firebaseStorageBucket,
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: _firebaseApiKeyIos,
        appId: _firebaseAppIdIos,
        messagingSenderId: _firebaseMessagingSenderId,
        projectId: _firebaseProjectId,
        storageBucket: _firebaseStorageBucket,
        iosClientId: _firebaseIosClientId,
        iosBundleId: _firebaseIosBundleId,
      );
}