// File generated by FlutterFire CLI, with the API keys moved to build-time
// defines (flutterfire configure would restore the hardcoded keys). Only the
// web app is kept: Firebase só roda na web (`nuvemSuportada` em
// lib/data/nuvem.dart); o Android nunca chama Firebase.initializeApp.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'Firebase só é usado na web (ver lib/data/nuvem.dart).',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_WEB'),
    appId: '1:169480227109:web:5115ed3308487da23c72cc',
    messagingSenderId: '169480227109',
    projectId: 'devocional-15815',
    authDomain: 'www.felipeambrozini.com.br',
    storageBucket: 'devocional-15815.firebasestorage.app',
    measurementId: 'G-2WLQXEVJ5S',
  );
}
